<?php

namespace Tests\Unit;

use App\Rules\OffsetRule;
use PHPUnit\Framework\TestCase;

class OffsetRuleTest extends TestCase
{
    /**
     * @var OffsetRule
     */
    protected OffsetRule $rule;

    public function setUp(): void
    {
       parent::setUp(); // TODO: Change the autogenerated stub
       $this->rule = new OffsetRule();
    }

    /**
     * @return \int[][]
     */
    public function validOffsetProvider()
    {
       return [
           [0],
           [20],
           [40],
           [160],
           [180]
       ];
    }

    /**
     * @return array
     */
    public function inValidOffsetProvider()
    {
       return [
           [null],
           [10],
           [4],
           [15],
           [90],
           [90.12332]
       ];
    }

    /**
     * @dataProvider validOffsetProvider
     * @param $offset
     * @return void
     */
    public function testValidOffsetPass($offset)
    {
        $this->assertTrue($this->rule->passes('offset',$offset));
    }

    /**
     * @dataProvider inValidOffsetProvider
     * @param $offset
     * @return void
     */
    public function testInValidOffsetFail($offset)
    {
        $this->assertFalse($this->rule->passes('offset',$offset));
    }
}
