<?php

namespace Tests\Unit;

use App\Rules\TitleRule;
use PHPUnit\Framework\TestCase;

class TitleRuleTest extends TestCase
{
    /**
     * @var TitleRule
     */
    protected TitleRule $rule;

    /**
     * @return void
     */
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->rule = new TitleRule();
    }

    /**
     * @return \string[][]
     */
    public function validTitleProvider()
    {
        return [
            ['I am good'],
            ['\b abcd \t']
        ];
    }

    /**
     * @return array
     */
    public function inValidTitleProvider()
    {
        return [
            [45],
            [4.5]
        ];
    }

    /**
     * @dataProvider validTitleProvider
     * @param $title
     * @return void
     */
    public function testTitleRulePass($title)
    {
        $this->assertTrue($this->rule->passes('title', $title));
    }

    /**
     * @dataProvider inValidTitleProvider
     * @param $title
     * @return void
     */
    public function testTitleRuleFail($title)
    {
        $this->assertFalse($this->rule->passes('title',$title));
    }

}
